### ISSUE TITLE
Move babel-preset-flow to devDependencies

### ISSUE THREAD

**Issue by edmorley** [bvaughn/highlight-words-core#11]
Hi :-)

`babel-preset-flow` has been added to `dependencies`, whereas it seems like it should be in `devDependencies`?
https://github.com/bvaughn/highlight-words-core/commit/6189dfee642e860e4ac1eab0653d479fd2c0f391#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R60

**Comment by bvaughn** [comment]
Oh whoops. That was clowny of me. Thanks for letting me know. Will fix as
soon as I get to my laptop.
