### ISSUE TITLE
Error when searchWords is immutable?

### ISSUE THREAD

**Issue by tleunen** [bvaughn/highlight-words-core#2]
I'm not sure why yet, but if `searchWords` is immutable, `findAll` is failing.

```
Error: The sort method cannot be invoked on an Immutable data structure.
```

Looks like it's this sort: https://github.com/bvaughn/highlight-words-core/blob/003b1511847544f8aa222e06cd9ef9165702ffd0/src/utils.js#L32
The content of `chunks` is immutable, and the objects inside as well.

But I don't see why/when `searchWords` gets modified.
It's used only in `findChunks`, and a new array is returned so I don't understand :/

I'll try to find the source later, but I'm creating the ticket in case you have an idea. FWIW, I'm using seamless-immutable.

**Comment by bvaughn** [comment]
seemless-immutable [bans](https://github.com/rtfeldman/seamless-immutable/blob/master/src/seamless-immutable.js#L45-L50) certain [methods](https://github.com/rtfeldman/seamless-immutable/blob/master/src/seamless-immutable.js#L88) typically associated with mutation. Pretty sure you'll need to convert it to an array or use a lib like ImmutableJS that supports sort. Sorry!
