### ISSUE TITLE
When enter special symbol like '+', app crushed

### ISSUE THREAD

**Issue by serhii-yalla** [bvaughn/highlight-words-core#28]
![image](https://github.com/user-attachments/assets/8f384bbc-7216-4a99-b665-6724083ac5cd)

Warning: SyntaxError: Invalid RegExp: Quantifier has nothing to repeat

Code, where crush happens:

```
const chunks = findAll({
    textToHighlight: String(textToHighlight),
    searchWords: [String(searchWords)],
    sanitize,
    autoEscape
  });
  ```

**Comment by serhii-yalla** [comment]
@bvaughn @sergei-startsev @edmorley @RichardBradley Any help?

**Comment by serhii-yalla** [comment]
P.S. Have installed latest version 1.2.3

**Comment by sergei-startsev** [comment]
@serhii-yalla Could you make sure `autoEscape` is set to `true`?

**Comment by serhii-yalla** [comment]
@sergei-startsev Yeah. ```autoEscape``` wasn't set as ```true```, so it crashed due to this. Appreciate help.
